DROP TABLE IF EXISTS ods_goods_raw;
CREATE TABLE IF NOT EXISTS ods_goods_raw (
    `goodsId` BIGINT COMMENT '商品id',
    `siteId` BIGINT COMMENT '商品采集站点',
    `date` DATE COMMENT '商品信息统计日期',
    `mallId` STRING COMMENT '商品所属店铺id',
    `sellerType` BIGINT COMMENT '商家类型编码',
    `currentSkuId` STRING COMMENT '当前skuid',
    `defaultSkuId` STRING COMMENT '默认的skuid',
    `selectedLang` STRING COMMENT '选择的语言',
    `lang` STRING COMMENT '语言',
    `selectedCurrency` STRING COMMENT '选择的货币单位',
    `optId` BIGINT COMMENT '前端类目id',
    `optType` BIGINT COMMENT 'optType',
    `optLevel` BIGINT COMMENT 'optLevel',
    `catId` BIGINT COMMENT '商家后台类目id',
    `catInfo` JSON COMMENT '商家后台类目的多层级id信息',
    `title` STRING COMMENT '商品标题',
    `goodsName` STRING COMMENT '商品标题',
    `linkUrl` STRING COMMENT '商品链接',
    `activityType` BIGINT COMMENT '活动类型',
    `sideSalesTip` STRING COMMENT '销售贴士',
    `salesTip` STRING COMMENT '销售贴士',
    `salesTipText` JSON COMMENT '销售文本列表',
    `salesTipTextList` JSON COMMENT '销售文本列表',
    `businessReduction` STRING COMMENT '商家承担优惠金额',
    `isOnsale` BIGINT COMMENT '是否在售',
    `isShowMarketPrice` BOOLEAN COMMENT '是否展示原价',
    `isSkc` BOOLEAN COMMENT '是否为skc',
    `qty` BIGINT COMMENT 'qty',
    `status` BIGINT COMMENT 'status',
    `soldOutSubscribeStatus` BIGINT COMMENT 'soldOutSubscribeStatus',
    `salesNum` BIGINT COMMENT '销售数量',
    `soldQuantity` BIGINT COMMENT '销售数量',
    `reviewNum` BIGINT COMMENT '评论数量',
    `commentNumTips` STRING COMMENT '评论数量提示',
    `sortTypeStyle` BIGINT COMMENT '评价列表排序样式标识',
    `goodsScore` DOUBLE COMMENT '商品评分',
    `showScore` DOUBLE COMMENT '商品评分',
    `reviewScore` STRING COMMENT '商品综合评价得分',
    `hiddenComment` BOOLEAN COMMENT '是否隐藏评论',
    `seoLinkUrl` STRING COMMENT 'seo链接',
    `defaultSelectSpec` JSON COMMENT '默认选择的规格',
    `minOnSalePrice` BIGINT COMMENT '销售价格最低值(单位分)',
    `maxOnSalePrice` BIGINT COMMENT '销售价格最高值(单位分)',
    `priceInfo` JSON COMMENT '价格信息',
    `salePriceRich` JSON COMMENT '销售价格富文本信息',
    `minToMaxSalePriceRich` JSON COMMENT 'minToMaxSalePriceRich',
    `image` JSON COMMENT '图片信息',
    `brandCard` JSON COMMENT '品牌卡片',
    `guideFile` JSON COMMENT '指导书文件',
    `hdThumbUrl` STRING COMMENT '缩略图链接',
    `thumbUrl` STRING COMMENT '略缩图链接',
    `goodsImage` STRING COMMENT '商品图片链接',
    `imageUrl` STRING COMMENT '商品图片链接',
    `longThumbUrl` STRING COMMENT '商品图片链接',
    `searchKey` STRING COMMENT '用户原始搜索关键词',
    `queryReleScore` DOUBLE COMMENT 'queryReleScore',
    `goodRankList` JSON COMMENT 'goodRankList',
    `video` JSON COMMENT '商品视频信息',
    `visible` BOOLEAN COMMENT '商品是否可见',
    `pageAlt` STRING COMMENT '商品页面描述信息',
    `itemType` BIGINT COMMENT 'itemType',
    `HWRatio` BIGINT COMMENT 'HWRatio',
    `semiManaged` BOOLEAN COMMENT '是否半托管',
    `benefitText` JSON COMMENT '折扣文本信息',
    `soldQuantityPercent` BIGINT COMMENT '销量占库存百分比(存疑)',
    `wareHouseType` BIGINT COMMENT '仓库类型',
    `isLocalGoods` BIGINT COMMENT '是否为本地商品',
    `itemId` STRING COMMENT 'itemId',
    `adultGoods` BOOLEAN COMMENT '是否为成人用品',
    `isManualChangeSpec` BOOLEAN COMMENT 'isManualChangeSpec',
    `topItemsSize` BIGINT COMMENT '商品在店铺的top排行榜索引',
    `topItemsTitle` STRING COMMENT '商品在店铺的top排行榜标题',
    `topItemsTitleBrief` STRING COMMENT '商品在店铺的top排行榜标题的解释',
    `topItemsTag` STRING COMMENT '商品在店铺的top排行榜的标签',
    `subTopItemsTitleUserText` STRING COMMENT '商品在店铺的top排行榜相关文本',
    `topItemsType` BIGINT COMMENT '商品所在店铺的top排行榜类型',
    `iterationSku` JSON COMMENT 'skuid列表',
    `clothFitReviewText` STRING COMMENT '衣服适配评论文本',
    `popupClothFitReviewText` STRING COMMENT '衣服适配评论文本',
    `clothFitReviewInfoList` JSON COMMENT '衣服适配的评论信息列表',
    `bestSellerModule` JSON COMMENT '畅销信息模块',
    `pageLabelsInfo` JSON COMMENT '商品评论标签信息',
    `gallery` JSON COMMENT '商品轮播图列表',
    `goodsProperty` JSON COMMENT '商品属性',
    `goodsPropertyPrefer` JSON COMMENT 'goodsPropertyPrefer',
    `bannerList` JSON COMMENT 'bannerList',
    `detailList` JSON COMMENT 'detailList',
    `customImageList` JSON COMMENT 'customImageList',
    `rows` BIGINT COMMENT 'rows',
    `statusExplain` STRING COMMENT 'statusExplain',
    `checkQuantity` BIGINT COMMENT 'checkQuantity',
    `sizeGuide` JSON COMMENT '尺码指南',
    `skcList` JSON COMMENT '商品的skc信息列表',
    `specIds` STRING COMMENT '规格id列表',
    `skuList` JSON COMMENT 'sku信息列表',
    `sizeSpecModule` JSON COMMENT '尺码表信息',
    `specCustom` JSON COMMENT '规格相关的信息',
    `productDetailFlatList` JSON COMMENT '商品详情图列表(展开)',
    `productDetail` JSON COMMENT '商品详情图信息',
    `ext` JSON COMMENT 'ext',
    `extendFields` JSON COMMENT 'extendFields',
    `activityInfo` JSON COMMENT '活动信息',
    `displayEndTime` BIGINT COMMENT '展示结束时间',
    `displayEndTimePercent` BIGINT COMMENT 'displayEndTimePercent',
    `displayEndTimePercentImg` STRING COMMENT 'displayEndTimePercentImg',
    `selectedSpecIds` JSON COMMENT 'selectedSpecIds',
    `quickLook` JSON COMMENT '快速预览信息',
    `crumbOptList` JSON COMMENT '类目信息列表',
    `tagsInfo` JSON COMMENT '商品标签信息',
    `tagCode` BIGINT COMMENT '店铺权益标签',
    `pRec` JSON COMMENT 'pRec',
    `userAgent` STRING COMMENT '浏览器userAgent头',
    `fromUrl` STRING COMMENT '数据来源url',
    `serverTime` STRING COMMENT '服务器时间戳',
    `timezone` STRING COMMENT '时区'
)
DUPLICATE KEY(`goodsId`, `siteId`, `date`)
COMMENT '商品原始表'
PARTITION BY RANGE(`date`) ()
DISTRIBUTED BY HASH(`goodsId`) BUCKETS 16
PROPERTIES (
    "replication_num" = "3",
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-2147483648",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "16"
);
